Repository wintercms/storm, pull requests merged in 2021-03, with the labels that each got.

#5 Revert changes that break belongsToMany relations
  src/Database/Relations/BelongsToMany.php
  src/Database/Relations/DefinedConstraints.php
  tests/Database/RelationsTest.php
Labels: Status: Completed, Type: Maintenance

#10 Allow for class aliases to be specified in plugin/module class loader
  src/Support/ClassLoader.php
  tests/Support/ClassLoaderTest.php
  tests/fixtures/classes/plugins/winter/plugin/classes/TestClass.php
  tests/fixtures/classes/plugins/winter/plugin/controllers/TestController.php
  tests/fixtures/classes/plugins/winter/plugin/models/TestModel.php
Labels: Status: Completed, Type: Enhancement

#12 Support saving deferred bindings with pivot data.
  src/Database/Migrations/2021_01_19_000001_Db_Add_Pivot_Data_To_Deferred_Bindings.php
  src/Database/Models/DeferredBinding.php
  src/Database/Relations/BelongsToMany.php
  src/Database/Relations/DeferOneOrMany.php
  src/Database/Traits/DeferredBinding.php
Labels: Status: Completed, Type: Enhancement

#6 Extend Laravel Events Dispatcher
  src/Events/Dispatcher.php
Labels: Status: Review Needed, Type: Maintenance

#15 Add support for namespace aliases in Class loader
  src/Support/ClassLoader.php
  tests/Support/ClassLoaderTest.php
Labels: Status: Completed, Type: Enhancement

#16 Update Symfony/Yaml to v4, add support for YAML processing
  composer.json
  src/Parse/Processor/Contracts/YamlProcessor.php
  src/Parse/Yaml.php
  tests/Parse/YamlTest.php
  tests/fixtures/yaml/test.yaml
Labels: Status: Response Needed, Type: Enhancement

#18 Add Symfony-3 compatible YAML processor for Yaml service
  composer.json
  src/Parse/ParseServiceProvider.php
  src/Parse/Processor/Symfony3Processor.php
  tests/Parse/YamlTest.php
  tests/fixtures/yaml/symfony3.yaml
Labels: Status: Completed, Type: Maintenance

#7 Add array views support to MailFake
  src/Support/Testing/Fakes/MailFake.php
  tests/Support/MailFakeTest.php
Labels: Status: Completed, Type: Enhancement
