Repository wintercms/storm, pull requests merged in 2022-07, with the labels that each got.

#93 [WIP] 1.2 - Fix Twig Compiling
  src/Foundation/Application.php
Labels: Type: Maintenance, Status: Completed

#92 Restore Laravel 6 behavior to public visibility for local driver
  src/Filesystem/FilesystemManager.php
Labels: Type: Maintenance, Status: Completed

#81 Can't pass null to non-nullable arguments
  src/Support/helpers.php
Labels: Type: Maintenance, Status: Completed

#96 Fix for placeholder default block
  src/Html/BlockBuilder.php
  tests/Html/BlockBuilderTest.php
Labels: Type: Maintenance, Priority: High, Status: Completed

#95 Prevent a urlencoded sub-URL in main URL path to be decoded.
  src/Router/UrlGenerator.php
  tests/Router/UrlGeneratorTest.php
Labels: Type: Maintenance, Priority: High

#97 Model: make string attribute value auto-trimming optional
  src/Database/Model.php
Labels: Type: Maintenance, Status: Completed

#94 [1.2] Sortable Relation trait
  phpstan-baseline.neon
  src/Database/Relations/BelongsTo.php
  src/Database/Relations/Concerns/AttachOneOrMany.php
  src/Database/Relations/Concerns/BelongsOrMorphsTo.php
  src/Database/Relations/Concerns/HasOneOrMany.php
  src/Database/Relations/Concerns/MorphOneOrMany.php
  src/Database/Relations/MorphTo.php
  src/Database/Traits/HasSortableRelations.php
Labels: Type: Enhancement, Status: Completed

#100 regenerate the resizer fixtures to fix failing tests
  tests/fixtures/resizer/target/testReset_testResize0x0_testResizeAutoLandscape1x1.png
  tests/fixtures/resizer/target/testResizeAutoExifRotated30x30.jpg
  tests/fixtures/resizer/target/testResizeAutoLandscape1x5.png
  tests/fixtures/resizer/target/testResizeAutoLandscape25.png
  tests/fixtures/resizer/target/testResizeAutoLandscape25x1.png
  tests/fixtures/resizer/target/testResizeAutoSquare25x50_testResizeAutoSquare50x25_testResizeAutoSquare50x50_testResizeFitSquare50x50.jpg
  tests/fixtures/resizer/target/testResizeExact10x15.jpg
  tests/fixtures/resizer/target/testResizeFitLandscape30x30.png
  tests/fixtures/resizer/target/testSharpen.jpg
Labels: Type: Maintenance, Status: Completed

#99 Use extension if provided in resizer options
  src/Database/Attach/Resizer.php
  tests/Database/Attach/ResizerTest.php
Labels: Type: Enhancement, Status: Completed
