Repository wintercms/storm, pull requests merged in 2022-06, with the labels that each got.

#87 Add Array Source trait
  .gitignore
  composer.json
  src/Database/Traits/ArraySource.php
  src/Foundation/Maker.php
  src/Halcyon/Processors/SectionParser.php
  src/Halcyon/Traits/Validation.php
  tests/Database/ModelTest.php
  tests/Database/QueryBuilderTest.php
  tests/Database/RelationsTest.php
  tests/Database/Traits/ArraySourceTest.php
  tests/Database/Traits/EncryptableTest.php
  tests/Database/Traits/PurgeableTraitTest.php
  tests/Database/Traits/SluggableTest.php
  tests/Database/Traits/ValidationTest.php
  tests/DbTestCase.php
  tests/Halcyon/HalcyonModelTest.php
  tests/Support/MailFakeTest.php
  tests/TestCase.php
Labels: Type: Enhancement, Status: Completed

#86 Load deferred providers before provider registration
  src/Cache/CacheServiceProvider.php
  src/Foundation/Application.php
  src/Foundation/ProviderRepository.php
  src/Redis/RedisServiceProvider.php
  tests/Foundation/ProviderRepositoryTest.php
  tests/tmp/.gitignore
Labels: Type: Maintenance, Status: Testing Needed

#90 Added additional test case for UrlGenerator class
  src/Router/UrlGenerator.php
  tests/Router/UrlGeneratorTest.php
Labels: Type: Maintenance, Status: Review Needed
