Repository wintercms/storm, pull requests merged in 2022-04, with the labels that each got.

#76 [WIP] Improve scaffolding commands
  src/Console/Command.php
  src/Foundation/Providers/ArtisanServiceProvider.php
  src/Scaffold/GeneratorCommand.php
  tests/Scaffold/ScaffoldBaseTest.php
Labels: Type: Enhancement, Status: Completed

#79 Fire mailer.beforeRegister event earlier
  src/Mail/MailManager.php
Labels: Type: Maintenance, Status: Review Needed

#82 Remove non-existent argument to Ini::parse() method call
  src/Halcyon/Processors/SectionParser.php
Labels: Type: Maintenance, Status: Completed
