Repository wintercms/storm, pull requests merged in 2023-08, with the labels that each got.

#147 Add json helper method to set payload as json-encoded value.
  src/Network/Http.php
Labels: Type: Maintenance, Status: Revision Needed

#150 Call model methods using event handler with default priority
  phpstan-baseline.neon
  src/Database/Model.php
  src/Database/Traits/SoftDelete.php
  src/Database/Traits/Validation.php
  src/Halcyon/Model.php
Labels: Type: Enhancement, Status: Completed

#154 Clear model cache when using upsert
  src/Database/Builder.php
  src/Database/QueryBuilder.php
  tests/Database/ModelTest.php
Labels: Type: Maintenance, Status: Completed
