Repository wintercms/storm, pull requests merged in 2024-04, with the labels that each got.

#137 Laravel 10 support
  .github/workflows/tests.yml
  composer.json
  src/Cache/CacheManager.php
  src/Console/Traits/HandlesCleanup.php
  src/Database/Concerns/HasAttributes.php
  src/Database/Model.php
  src/Database/Relations/Concerns/DeferOneOrMany.php
  src/Flash/FlashBag.php
  src/Foundation/Application.php
  src/Foundation/Http/Kernel.php
  src/Halcyon/Builder.php
  src/Halcyon/Model.php
  src/Support/Facades/DB.php
  src/Support/Facades/Mail.php
  src/Translation/FileLoader.php
  tests/Database/ModelTest.php
  tests/Database/UpdaterTest.php
  tests/Foundation/ApplicationTest.php
  tests/Html/BlockBuilderTest.php
  tests/Support/EventFakeTest.php
  tests/Support/MailFakeTest.php
  tests/Translation/FileLoaderTest.php
Labels: Status: In Progress, Type: Enhancement

#157 Laravel 10
  .github/workflows/code-analysis.yaml
  .github/workflows/code-quality.yaml
  .github/workflows/tests.yml
  .gitignore
  composer.json
  src/Auth/Models/Throttle.php
  src/Database/Concerns/HasRelationships.php
  src/Database/Model.php
  src/Database/QueryBuilder.php
  src/Database/Relations/Concerns/DeferOneOrMany.php
  src/Database/Relations/MorphToMany.php
  src/Database/Traits/Revisionable.php
  src/Foundation/Application.php
  src/Foundation/Http/Middleware/CheckForMaintenanceMode.php
  src/Support/Facades/Flash.php
  src/Support/Facades/Mail.php
Labels: Type: Maintenance, Status: Revision Needed, Status: Review Needed

#172 Fix HasOneThrough / HasManyThrough relationships
  .github/workflows/code-analysis.yaml
  .github/workflows/tests.yml
  phpstan-baseline.neon
  phpstan.neon
  src/Database/Concerns/HasRelationships.php
  src/Database/Relations/Concerns/DefinedConstraints.php
Labels: Type: Maintenance, Status: Completed

#174 Fix paginate & simplePaginate for BelongsToOrMorpsMany Relationships
  phpstan-baseline.neon
  src/Database/Relations/Concerns/BelongsOrMorphsToMany.php
Labels: Type: Maintenance, Status: Completed
