Repository wintercms/storm, pull requests merged in 2025-02, with the labels that each got.

#201 Improve support for Factories
  src/Database/Factories/Factory.php
  src/Database/Factories/HasFactory.php
  tests/Database/Factories/FactoryTest.php
Labels: Type: Maintenance

#204 Added support for more detailed error logging
  src/Foundation/Exception/Handler.php
Labels: Type: Enhancement

#203 Improve PHP 8.4 support
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .github/workflows/tests.yml
  src/Argon/Argon.php
  src/Auth/AuthenticationException.php
  src/Database/Concerns/HasRelationships.php
  src/Exception/ApplicationException.php
  src/Exception/ExceptionBase.php
  src/Exception/SystemException.php
  src/Halcyon/Datasource/Resolver.php
  src/Halcyon/Datasource/ResolverInterface.php
  src/Html/BlockBuilder.php
  src/Html/FormBuilder.php
  src/Html/HtmlBuilder.php
  src/Mail/Mailer.php
  src/Network/Http.php
  src/Support/helpers-array.php
Labels: Type: Maintenance, Status: Completed

#205 Fix PHP8.4 errors with symfony/console
  .github/workflows/code-quality.yaml
  .github/workflows/tests.yml
  composer.json
  src/Console/Traits/HandlesCleanup.php
Labels: Type: Maintenance, Status: Blocked

#198 Unset event handler when halting
  src/Support/Traits/Emitter.php
  tests/Support/EmitterTest.php
Labels: Type: Maintenance, Status: Completed

#202 Fix Syntax Error in CAST Statement for Postgres Attachment Count Query
  src/Database/Relations/Concerns/AttachOneOrMany.php
Labels: Type: Bug, Status: Completed
